destination: docs
#Build Settings
title: SIA(SAUBER INSTITUTION AGENCY)
remote_theme: pages-themes/architect@v0.2.0

# Sidebar settings
sidebar: true                       
sidebar-about-description: "TRY EVERYTHINGs"